language: java
jdk: openjdk8
dist: xenial

# Overridden because parent project uses maven.test.skip instead of skipTests
install: mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn package
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report

after_success:
  - >
    mvn com.gavinmogan:codacy-maven-plugin:coverage \
      -DcoverageReportFile=target/site/jacoco/jacoco.xml \
      -DprojectToken="${PROJECT_TOKEN}" -DapiToken="${API_TOKEN}"

cache:
  directories:
  - $HOME/.m2

# The only branch we build on is master; all other builds are done on PRs to master
branches:
  only:
  - master

notifications:
  email:
    recipients:
    - ksclarke@ksclarke.io
    on_failure: change
    on_success: change

sudo: false
